language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION='Django>=1.11,<2.0'
  - DJANGO_VERSION='Django>=2.0,<2.1'
  - DJANGO_VERSION='Django>=2.1,<2.2'
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "2.7"
      env: DJANGO_VERSION='Django>=2.0,<2.1'
    - python: "2.7"
      env: DJANGO_VERSION='Django>=2.1,<2.2'
    - python: "3.4"
      env: DJANGO_VERSION='Django>=2.1,<2.2'
    - python: "3.4"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

install:
  - pip install -q $DJANGO_VERSION
  - pip install coveralls
  - if [[ $(python -c 'import sys; print("0" if sys.version_info < (3,6) else "1")') == "1" ]]; then pip install black; fi

script:
  - coverage erase
  - if [[ $(python -c 'import sys; print("0" if sys.version_info < (3,6) else "1")') == "1" ]]; then black . --check; fi
  - PYTHONPATH=. coverage run -p example/run_tests.py
  - PYTHONPATH=. coverage run -p example/run_tests.py example.settings_no_debug
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - ignas@idenfy.com